import api from './api.js'

export const getProducts = (category = '', availability = 'available', offersOnly = false) => api(`/products?${category ? `category=${encodeURIComponent(category)}&` : ''}${availability === 'all' ? 'availability=all&' : ''}${offersOnly ? 'offers=true' : ''}`, { suppressError: true })
export const getOffers = () => getProducts('', 'available', true)
export const getProduct = (id) => api(`/products/${id}`, { suppressError: true })
export const getAdminProducts = () => api('/admin/products')
export const createProduct = (data) => api('/admin/products', { method: 'POST', body: JSON.stringify(data) })
export const updateProduct = (id, data) => api(`/admin/products/${id}`, { method: 'PATCH', body: JSON.stringify(data) })
export const updateProductVariants = (id, variants) => api(`/admin/products/${id}/variants`, { method: 'PUT', body: JSON.stringify({ variants }) })
export const saveProductAndVariants = (id, data, variants) => api(`/admin/products/${id}`, { method: 'PUT', body: JSON.stringify({ ...data, variants }) })
export const attachProductMedia = (id, mediaId, displayOrder) => api(`/admin/products/${id}/media`, { method: 'POST', body: JSON.stringify({ mediaId, displayOrder }) })
export const deleteProductMedia = (id, mediaId) => api(`/admin/products/${id}/media`, { method: 'DELETE', body: JSON.stringify({ mediaId }) })
export const deleteProduct = (id) => api(`/admin/products/${id}`, { method: 'DELETE' })
export const getProductReviews = (id) => api(`/products/${id}/reviews`, { suppressError: true })
export const createReview = (id, data) => api(`/products/${id}/reviews`, { method: 'POST', body: JSON.stringify(data) })
export const updateReview = (id, reviewId, data) => api(`/products/${id}/reviews/${reviewId}`, { method: 'PATCH', body: JSON.stringify(data) })
export const deleteReview = (id, reviewId) => api(`/products/${id}/reviews/${reviewId}`, { method: 'DELETE' })
export const createAdminReview = (id, data) => api(`/admin/products/${id}/reviews`, { method: 'POST', body: JSON.stringify(data) })
export const updateAdminReview = (id, reviewId, data) => api(`/admin/products/${id}/reviews/${reviewId}`, { method: 'PATCH', body: JSON.stringify(data) })
export const deleteAdminReview = (id, reviewId) => api(`/admin/products/${id}/reviews/${reviewId}`, { method: 'DELETE' })
